import PageLayout from "@/components/PageLayout";
import { motion } from "framer-motion";

const TermsPage = () => (
  <PageLayout>
    <section className="section-padding blue-ambient">
      <div className="mx-auto max-w-4xl">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          <h1 className="font-display text-4xl font-bold text-foreground md:text-5xl mb-8">Terms of Service</h1>
          <p className="text-muted-foreground mb-8">Last updated: February 2026</p>

          <div className="space-y-8 text-sm text-muted-foreground leading-relaxed">
            <div>
              <h2 className="font-display text-lg font-semibold text-foreground mb-3">1. Acceptance of Terms</h2>
              <p>By accessing or using VANTORY, you agree to be bound by these Terms of Service. If you do not agree, please do not use the platform.</p>
            </div>
            <div>
              <h2 className="font-display text-lg font-semibold text-foreground mb-3">2. Description of Service</h2>
              <p>VANTORY provides AI-powered workforce automation tools including social media management, customer support, email marketing, and calendar assistant capabilities for small businesses.</p>
            </div>
            <div>
              <h2 className="font-display text-lg font-semibold text-foreground mb-3">3. User Responsibilities</h2>
              <p>You are responsible for maintaining the security of your account, ensuring the accuracy of connected platform credentials, and reviewing AI-generated content before publishing or sending.</p>
            </div>
            <div>
              <h2 className="font-display text-lg font-semibold text-foreground mb-3">4. AI-Generated Content</h2>
              <p>Content generated by VANTORY's AI employees is created to assist you. You retain full control and responsibility over all content that is published, sent, or shared through your connected platforms.</p>
            </div>
            <div>
              <h2 className="font-display text-lg font-semibold text-foreground mb-3">5. Billing & Cancellation</h2>
              <p>Paid plans are billed monthly or annually. You may cancel at any time. Refunds are handled on a case-by-case basis within the first 14 days of a new subscription.</p>
            </div>
            <div>
              <h2 className="font-display text-lg font-semibold text-foreground mb-3">6. Limitation of Liability</h2>
              <p>VANTORY is provided "as is." We are not liable for any damages arising from your use of AI-generated content or platform integrations. Always review outputs before taking action.</p>
            </div>
            <div>
              <h2 className="font-display text-lg font-semibold text-foreground mb-3">7. Contact</h2>
              <p>For questions about these terms, please reach out to <a href="mailto:support@aivantory.com" className="text-primary hover:underline">support@aivantory.com</a> or call <a href="tel:+18067794074" className="text-primary hover:underline">+1 (806) 779-4074</a>.</p>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  </PageLayout>
);

export default TermsPage;
